const express = require("express");
const router = express.Router();
const { updateParking } = require("../controllers/updateParking");
const { createorder } = require("../controllers/createParking");
const { getparking } = require("../controllers/getparking");
const { createordernew } = require("../controllers/create_order");
const { updateorders } = require("../controllers/update_order");
const { updateordersdelivered } = require("../controllers/deliver_order");
const { getorders } = require("../controllers/get_orders");
const { getundeliveredorders } = require("../controllers/get_undelivered_orders");
const { creattable } = require("../controllers/create_table");
const { getTables } = require("../controllers/get_table");
const { getitems } = require("../controllers/get_items");
const { createitems } = require("../controllers/create_items");
const { updateitems } = require("../controllers/update_availability");
router.post("/update", updateParking);
router.post("/create", createorder);
router.post("/getaddress", getparking);
router.post("/createorder", createordernew);
router.post("/updateorders", updateorders);
router.post("/updateordersdelivered", updateordersdelivered);
router.post("/creattable", creattable);
router.post("/createitems", createitems);
router.post("/updateitems", updateitems);
router.get("/getorders", getorders);
router.get("/gettables", getTables);
router.get("/getitems", getitems);
router.get("/getundeliveredorders", getundeliveredorders);
module.exports = router;
